project:
  type: website

website:
  title: "Nithin M"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  navbar:
    right:
      - text: CV
        href: my-new-cv.pdf
      - text : Employment
        href: employment.qmd
    left:
      - text: "{{< fa atom  >}} Research"
        href: research.qmd
      - text: "{{< fa comments  >}} Talks"
        href: talks.qmd
      - text: Blog
        href: blog/index.qmd
      - text: Contact
        href: contact.qmd
  page-footer: 
    background: "#eeffee"
format:
  html:
    backgroundcolor: "#eeffee"
    fontsize: 20px
    theme: [cosmo, styles.scss]
execute:
  cache: true

