project:
  type: website

website:
  title: "Nithin M"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  navbar:
    right:
      - text: CV
        href: my-new-cv.pdf
    left:
      - text: Research
        icon: atom
        href: research.qmd
      - text: Talks
        icon: comments
        href: talks.qmd
  page-footer: 
    background: "#eeffee"
  
      
format:
  html:
    backgroundcolor: "#eeffee"
    fontsize: 20px
    theme: [cosmo, styles.scss]

