[project]
name = "nithinmkp-github-io"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.3.0",
    "polars>=1.30.0",
    "ttictoc>=0.5.6",
]
