---
title: "Talks/Invited Lectures"
---

:::{.page-intro}
Selected invited lectures and talks on data analysis, reproducible research, and economics-oriented computing.
:::

## Invited Lectures

:::{.talk-list}
:::{.talk-card}
### Econtrix-26

**Flame University and Economiga**  
*3-5 January 2026*

Served as a resource person for the workshop and handled sessions on **web scraping using R and Python** and **time series analysis using R**.

[Website](https://nithinmkp.github.io/flame-economiga/)
:::

:::{.talk-card}
### Data Analysis using R

**Kerala Economic Association and Inter University Centre for Alternative Economics, University of Kerala**  
*25-29 August 2025*

Invited resource person at a five-day national workshop on data analysis using R.

[Slides](https://christ-r-talk.netlify.app)
:::

:::{.talk-card}
### Data Analysis using R (Hands-on Experience)

**Presidency University, Bangalore**  
*Online, 2024*

Delivered a session on using R for data analysis as part of the Faculty Development Program on Advanced Research Methodology and Data Analysis.

[Slides](https://christ-r-talk.netlify.app)
:::

:::{.talk-card}
### Using R for Data Analysis

**Central University of South Bihar**  
*Gaya, Bihar, 2022*

Invited lecture introducing R for social science researchers.
:::
:::

## Talks

:::{.talk-list}
:::{.talk-card}
### What Grad School Don't Teach You: Tools for Transparent and Reproducible Research

**YSI-Economiga Monsoon School 2025**  
*Workshop session*

Delivered a session on reproducible research workflows using Git, Quarto, R, and Python. A previous version of this talk was presented at a pre-conference session of the KEA Conference 2025.

[Materials](https://nithinmkp.github.io/ysi-economiga/)
:::

:::{.talk-card}
### Purrr, A Multipurpose Package

**Boston R Users Group**  
*Remote, 2021*

Lightning talk on one of my preferred R packages, `purrr`.
:::

:::{.talk-card}
### A Sneak Peek into R for Economics

**Economiga**  
*Remote, 2021*

Live talk on using R in economics research.

[Watch the talk](https://www.youtube.com/watch?v=vdD1w5_UGZs) | [Event details](https://www.economiga.org/econtalks/a-sneak-peek-into-r-for-economics)
:::
:::
